### ISSUE TITLE
GEXF File Format does not display in Gephi

### ISSUE THREAD

**Issue by Skyrant** [woj-ciech/kupa3#1]
The gexf file written does not load into Gephi. Is there any way to use the output in Gephi?

**Comment by Skyrant** [comment]
Since i have no X installed i added this to the very beginning of the kupa3.py file

```
import matplotlib
matplotlib.use('Agg')
```

It runs fine with default but when i try to load the file in Gephi it displays nothing

GEphi complains about the format but that should not be an issue since nx does not support 1.3 yet any ways. https://i.imgur.com/FHPgGMb.png

**Comment by Skyrant** [comment]
This is as far as i got with Gephi. The nodes are there but no labels: https://i.imgur.com/p7nHGkf.png

**Comment by woj-ciech** [comment]
I tested it on Kali Linux, with lot of domains and have no issues at all. I'm pretty sure that there is a problem with your setup. Does it occur with every domain? Do you have your Gephi updated? Do you see any data in Data Laboratory?

**Comment by woj-ciech** [comment]
So you should choose a layout and transformation first, I used Force Atlas 2, and then color your nodes and turn on labels (Click the small 'T' letter on the left corner). You can find quick intro here --> http://www.martingrandjean.ch/gephi-introduction/

**Comment by Skyrant** [comment]
That worked. Thanks!

**Comment by Skyrant** [comment]
My real issue is that i wanted it to work in the web version of Gephi but it's still empty there. MAybe if i convert the file with desktop Gephi first.

**Comment by Skyrant** [comment]
Yeah, exporting it with Gephi after setting colors and labels etc. works!

**Comment by Skyrant** [comment]
Thanks for the nice tool. Appreciate your help!

**Comment by woj-ciech** [comment]
You are welcome mate.
